# Storage backend: sqlite or json
storage:
  type: sqlite
  sqlite:
    file: polls.db
  json:
    file: polls.json

# Book customization using MiniMessage formatting
books:
  creation:
    title: "<gradient:#FFB833:#FF5733>Poll Creator</gradient>"
    author: "Polls"
    header: "<gold>Create a new poll</gold>\n"
    editQuestionButton: "<aqua>[Edit Question]</aqua>"
    editDurationButton: "<aqua>[Edit Duration]</aqua>"
    publishButton: "<green>[Publish Poll]</green>"
    cancelButton: "<red>[Cancel]</red>"
    optionButtonFormat: "<yellow>[Set Option {index}]</yellow>"
    optionUnset: "<black>[Not Set]"
    pageNote: "<black>Set up to 6 options. Use buttons to edit.</black>"
  voting:
    title: "<gradient:#FFB833:#FF5733>Community Poll</gradient>"
    author: "Polls"
    headerFormat: "<gold>Q:</gold> <white>{question}</white>\n<black>Closes:</black> <white>{closes_at}</white>\n"
    optionLineFormat: "{icon} <white>{option}</white> <black>(click to vote)</black>"
    alreadyVotedLineFormat: "{icon} <white>{option}</white> <black>(you voted)</black>"

# Customizable icons used before option text
icons:
  default:
    - "<yellow>1.</yellow>"
    - "<yellow>2.</yellow>"
    - "<yellow>3.</yellow>"
    - "<yellow>4.</yellow>"
    - "<yellow>5.</yellow>"
    - "<yellow>6.</yellow>"
