# Storage backend: sqlite or json
storage:
  type: sqlite
  sqlite:
    file: polls.db
  json:
    file: polls.json

# Book customization using MiniMessage formatting
books:
  creation:
    title: "<gradient:#7BD3EA:#2176FF>Poll Creator</gradient>"
    author: "Polls"
    header: "<gray>Create a new poll</gray>\n"
    editCodeButton: "<blue>[Edit Code]</blue>"
    editQuestionButton: "<blue>[Edit Question]</blue>"
    editDurationButton: "<blue>[Edit Duration]</blue>"
    publishButton: "<green>[Publish Poll]</green>"
    cancelButton: "<red>[Cancel]</red>"
    optionButtonFormat: "<gray>[Set Option {index}]</gray>"
    optionUnset: "<dark_gray>[Not Set]"
    pageNote: "<gray>Set up to 6 options. Use buttons to edit.</gray>"
    nextPageNote: "<dark_gray>Turn page to continue →</dark_gray>"
    indent: "  "
    labels:
      id: "<gray>Code:</gray>"
      question: "<gray>Question:</gray>"
      duration: "<gray>Duration:</gray>"
    autoReopen:
      enabled: true
      intervalTicks: 20
      onlyWhenIdle: true
    hover:
      code: "<gray>Click to set code</gray>"
      question: "<gray>Click to set question</gray>"
      duration: "<gray>Click to set duration</gray>"
      option: "<gray>Click to set option {index}</gray>"
      publish: "<green>Click to publish</green>"
      cancel: "<red>Click to cancel</red>"
  voting:
    title: "<gradient:#7BD3EA:#2176FF>Community Poll</gradient>"
    author: "Polls"
    headerFormat: "<gray>Q:</gray> <dark_gray>{question}</dark_gray>\n<gray>Closes:</gray> <dark_gray>{closes_at}</dark_gray>\n"
    closedMessage: "<red>Poll has closed</red>"
    labels:
      question: "<gray>Q:</gray>"
      closes: "<gray>Closes:</gray>"
    maxQuestionLength: 100
    maxOptionLength: 50
    optionLineFormat: "{icon} <dark_gray>{option}</dark_gray> <gray>(click to vote)</gray>"
    alreadyVotedLineFormat: "{icon} <dark_gray>{option}</dark_gray> <gray>(you voted)</gray>"
    rows:
      rowFormat: "%icon% <dark_gray>%question%</dark_gray> <gray>(%state%)</gray>"
    nextPageNote: "<dark_gray>Turn page to continue →</dark_gray>"
    indent: "  "
    state:
      # States for open polls
      click: "<gray>Click to vote for %number%</gray>"
      voted: "<yellow>You voted for %number%</yellow>"
      majority: "<green>%number% has most votes</green>"
      click_closed: "<gray>Voting closed</gray>"
      voted_closed: "<yellow>You voted for %number%</yellow>"
      majority_closed: "<green>%number% had highest votes</green>"
    hover:
      option: "<gray>Pick this option.</gray>"
      alreadyVotedOption: "<yellow>You already voted</yellow>"
      question: "<gray>Poll question</gray>"

# Customizable icons used before option text
icons:
  default:
    - "<dark_gray>1.</dark_gray>"
    - "<dark_gray>2.</dark_gray>"
    - "<dark_gray>3.</dark_gray>"
    - "<dark_gray>4.</dark_gray>"
    - "<dark_gray>5.</dark_gray>"
    - "<dark_gray>6.</dark_gray>"

# Sound customization for UX feedback
sounds:
  enabled: true
  ui:
    open_creation: "ui.button.click"
    set_value: "ui.button.click"
    error: "entity.villager.no"
    publish: "entity.player.levelup"
    cancel: "entity.item.break"
